version: "3"
services:
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID} #* 
        - GROUP_ID=${GROUP_ID} #* 
        - USER=${USER_NAME} #*
    ports:
      - "${JUPYTER_PORT}:8888" #*
    expose:
      - "8888"
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY} #*
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}
    volumes:
      - ./:/home/${USER_NAME}/work #*
      - ${LOCAL_DATA_PATH}:/home/${USER_NAME}/data/ #*
    command: "pip install -e /home/victor/work"
    deploy:
        replicas: 1
        restart_policy:
            condition: on-failure
        resources:
            reservations:
                devices:
                    - capabilities:
                        - gpu