# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"show_cam_motion": "cam.ipynb",
         "StandardizeGlobal": "core.ipynb",
         "StandardizeItem": "core.ipynb",
         "StandardizeNoDecode": "core.ipynb",
         "TensorMotion": "core.ipynb",
         "ToTensorMotion": "core.ipynb",
         "MotionBlock": "core.ipynb",
         "TensorTSMotion": "core.ipynb",
         "ToTensorTSMotion": "core.ipynb",
         "prettify_plot_TensorTSMotion": "core.ipynb",
         "load_poincare_maps": "data.ipynb",
         "load_index_file": "data.ipynb",
         "load_poincare_index_pair": "data.ipynb",
         "TSDataChaos": "data.ipynb",
         "get_motion_items": "data.ipynb",
         "show_labelled_ic_map": "data.ipynb",
         "x_sequence_length": "experiments.ipynb",
         "x_next_epsilon": "experiments.ipynb",
         "x_labelling_method": "experiments.ipynb",
         "df_slicer": "utils.ipynb",
         "ClassificationInterpretationAugmented": "utils.ipynb"}

modules = ["cam.py",
           "core.py",
           "data.py",
           "experiments.py",
           "utils.py"]

doc_url = "https://vrodriguezf.github.io/mlchaos/"

git_url = "https://github.com/vrodriguezf/mlchaos/tree/master/"

def custom_doc_links(name): return None
